FROM python:3.12.9-alpine3.21

WORKDIR /bot

COPY . .

RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt

ARG DB_IS_CREATED_ARG
ARG DB_DBMS_ARG
ARG DB_HOST_ARG
ARG DB_PORT_ARG
ARG DB_USER_ARG
ARG DB_PASS_ARG
ARG DB_NAME_ARG
ARG DB_ECHO_ARG
ARG DB_SQLite_ARG
ARG API_TOKEN_TG_ARG
ARG API_LINGVANEX_ARG
ARG API_GOOGLE_TRANSLATE_ARG

ENV DB_IS_CREATED=$DB_IS_CREATED_ARG
ENV DB_DBMS=$DB_DBMS_ARG
ENV DB_HOST=$DB_HOST_ARG
ENV DB_PORT=$DB_PORT_ARG
ENV DB_USER=$DB_USER_ARG
ENV DB_PASS=$DB_PASS_ARG
ENV DB_NAME=$DB_NAME_ARG
ENV DB_ECHO=$DB_ECHO_ARG
ENV DB_SQLite=$DB_SQLite_ARG
ENV API_TOKEN_TG=$API_TOKEN_TG_ARG
ENV API_LINGVANEX=$API_LINGVANEX_ARG
ENV API_GOOGLE_TRANSLATE=$API_GOOGLE_TRANSLATE_ARG

CMD ["python", "Bot_tg.py"]