select_USER_TG_ID_from_USERS_by_USER_TG_ID = """
SELECT USER_TG_ID FROM USERS
WHERE USER_TG_ID = %(USER_TG_ID)s;
"""

select_all_from_SURVEYS_ANSWERS_by_SURVEY_ID = """
SELECT * FROM SURVEYS_ANSWERS WHERE SURVEY_ID = %(SURVEY_ID)s;
"""

select_all_from_CONSTANTS_by_CONSTANT_NAMES = """
SELECT CONSTANT_VALUES FROM CONSTANTS
WHERE CONSTANT_NAMES = %(CONSTANT_NAMES)s;
"""

select_SURVEY_NAME_from_SURVEY = """
SELECT SURVEY_NAME FROM SURVEYS;
"""

select_SURVEY_ID_from_SURVEY_by_SURVEY_NAME = """
SELECT SURVEY_ID FROM SURVEYS WHERE SURVEY_NAME = %(SURVEY_NAME)s;"""

select_SURVEY_QUESTION_from_SURVEYS_ANSWERS_by_NUMBER_QUESTION_and_SURVEY_ID = """
SELECT SURVEY_QUESTION FROM SURVEYS_QUESTIONS
WHERE NUMBER_QUESTION = %(NUMBER_QUESTION)s and SURVEY_ID = %(SURVEY_ID)s;"""

select_ANSWERS_from_SURVEYS_ANSWERS_by_NUMBER_QUESTION_and_SURVEY_ID = """
SELECT ANSWER FROM SURVEYS_ANSWERS
WHERE NUMBER_QUESTION = %(NUMBER_QUESTION)s and SURVEY_ID = %(SURVEY_ID)s;"""

select_ANSWER_USER_from_SURVEYS_ANSWERS_by_NUMBER_QUESTION_and_SURVEY_ID_and_NUMBER_ANSWER = """
SELECT ANSWER FROM SURVEYS_ANSWERS
WHERE NUMBER_QUESTION = %(NUMBER_QUESTION)s and SURVEY_ID = %(SURVEY_ID)s and NUMBER_ANSWER = %(NUMBER_ANSWER)s;"""

select_COUNT_QUESTION_from_SURVEYS_QUESTIONS_by_SURVEY_ID = """
SELECT COUNT(SURVEY_ID) FROM BOT.SURVEYS_QUESTIONS
WHERE SURVEY_ID = %(SURVEY_ID)s;"""

insert_SURVEYS_by_SURVEY_NAME_and_SURVEY_DESCRIPTION = """
INSERT INTO SURVEYS (SURVEY_NAME, SURVEY_DESCRIPTION) VALUES (%(SURVEY_NAME)s, %(SURVEY_DESCRIPTION)s);
"""

insert_SURVEYS_QUESTIONS_by_SURVEY_ID_and_NUMBER_QUESTION_and_SURVEY_QUESTION = """
INSERT INTO SURVEYS_QUESTIONS (SURVEY_ID, NUMBER_QUESTION, SURVEY_QUESTION)
 VALUES (%(SURVEY_ID)s, %(NUMBER_QUESTION)s, %(SURVEY_QUESTION)s);
"""

insert_SURVEYS_TRUE_ANSWERS_by_SURVEY_ID_and_NUMBER_QUESTION_and_NUMBER_TRUE_ANSWER = """
INSERT INTO SURVEYS_TRUE_ANSWERS (SURVEY_ID, NUMBER_QUESTION, NUMBER_TRUE_ANSWER)
 VALUES (%(SURVEY_ID)s, %(NUMBER_QUESTION)s, %(NUMBER_TRUE_ANSWER)s);
"""

insert_SURVEYS_ANSWERS_by_NUMBER_ANSWER_and_SURVEY_ID_and_NUMBER_QUESTION_and_SURVEY_ANSWER = """
INSERT INTO SURVEYS_ANSWERS (NUMBER_ANSWER, SURVEY_ID, NUMBER_QUESTION, SURVEY_ANSWER)
 VALUES (%(NUMBER_ANSWER)s, %(SURVEY_ID)s, %(NUMBER_QUESTION)s, %(SURVEY_ANSWER)s);
"""

insert_USERS_by_USER_TG_ID_and_USER_FULL_NAME_and_USER_LOGIN = """
INSERT INTO USERS (USER_TG_ID, USER_FULL_NAME, USER_LOGIN)
 VALUES (%(USER_TG_ID)s, %(USER_FULL_NAME)s, %(USER_LOGIN)s)
 """


delete_USER_from_USERS_by_USER_TG_ID = """
DELETE FROM USERS
WHERE USER_TG_ID = %(USER_TG_ID)s;
"""