select_all_from_SURVEYS_ANSWERS_by_SURVEY_ID = """
SELECT * FROM SURVEYS_ANSWERS WHERE SURVEY_ID = %(SURVEY_ID)s;
"""

select_all_from_CONSTANTS_by_CONSTANT_NAMES = """
SELECT CONSTANT_VALUES FROM BOT.CONSTANTS
WHERE CONSTANT_NAMES = %(CONSTANT_NAMES)s;
"""

select_SURVEY_NAME_from_SURVEY = """
SELECT SURVEY_NAME FROM SURVEYS;
"""

select_SURVEY_ID_from_SURVEY_by_SURVEY_NAME = """
SELECT SURVEY_ID FROM BOT.SURVEYS WHERE SURVEY_NAME = %(SURVEY_NAME)s;"""

select_SURVEY_QUESTION_from_SURVEYS_ANSWERS_by_NUMBER_QUESTION_and_SURVEY_ID = """
SELECT SURVEY_QUESTION FROM BOT.SURVEYS_ANSWERS
WHERE NUMBER_QUESTION = %(NUMBER_QUESTION)s and SURVEY_ID = %(SURVEY_ID)s;"""

select_ANSWERS_from_SURVEYS_ANSWERS_by_NUMBER_QUESTION_and_SURVEY_ID = """
SELECT
 SURVEY_ANSWER_1,
 SURVEY_ANSWER_2,
 SURVEY_ANSWER_3,
 SURVEY_ANSWER_4
 FROM BOT.SURVEYS_ANSWERS
WHERE NUMBER_QUESTION = %(NUMBER_QUESTION)s and SURVEY_ID = %(SURVEY_ID)s;"""