select_all_from_SURVEYS_ANSWERS_by_SURVEY_ID = """
SELECT * FROM SURVEYS_ANSWERS WHERE SURVEY_ID = %(SURVEY_ID)s;
"""

select_all_from_CONSTANTS_by_CONSTANT_NAMES = """
SELECT CONSTANT_VALUES FROM BOT.CONSTANTS
WHERE CONSTANT_NAMES = %(CONSTANT_NAMES)s;
"""

select_SURVEY_NAME_from_SURVEY = """
SELECT SURVEY_NAME FROM SURVEYS
"""
